arch:
  arm64

os:
  linux

dist:
  focal

language:
  python

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12

virtualenv:
  system-site-packages: true

addons:
  apt:
    packages:
      - git
      - python3-pip

before_install:
  - chmod +x install.sh

install:
  - python3 -m pip install -r requirements.txt -r requirements_dev.txt
  - ./install.sh

script:
  - python3 -m pytest -m "not slow"

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients:
      - ${EMAIL}
    on_success: never
    on_failure: always